// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqulgfktatzbtzicskqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xdWxnZmt0YXR6YnR6aWNza3FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDY5NzAsImV4cCI6MjA2NzI4Mjk3MH0.jdnzUkw1l27cvviTSLQIE_rIVM8S2aR8fCNjA_ro6i0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});